@extends('layouts.app')
@section('title','Direktori UMKM | Desa Pringanom')
@section('content')
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<section class="page-container" x-data="{q:'',kategori:'',dusun:''}"><x-page-header eyebrow="Ekonomi Desa" title="Direktori & Peta UMKM" description="Temukan produk dan usaha warga Desa Pringanom." />
<div class="content-card mt-10 grid gap-4 p-5 md:grid-cols-3"><input x-model="q" placeholder="Cari nama UMKM atau pemilik" class="rounded-xl border-slate-300"><select x-model="kategori" class="rounded-xl border-slate-300"><option value="">Semua kategori</option>@foreach($categories as $v)<option>{{ $v }}</option>@endforeach</select><select x-model="dusun" class="rounded-xl border-slate-300"><option value="">Semua dusun</option>@foreach($dusuns as $v)<option>{{ $v }}</option>@endforeach</select></div>
<div id="umkm-map" class="mt-8 h-[420px] overflow-hidden rounded-2xl border border-slate-200"></div><a href="{{ asset('images/peta-sebaran-umkm.pdf') }}" download class="primary-button mt-5">Unduh Peta Sebaran UMKM (PDF/Gambar)</a>
<div class="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">@foreach($umkms as $u)<article class="content-card overflow-hidden" x-show="(!q||'{{ strtolower(addslashes($u->nama_umkm.' '.$u->pemilik)) }}'.includes(q.toLowerCase()))&&(!kategori||kategori==='{{ addslashes($u->kategori) }}')&&(!dusun||dusun==='{{ addslashes($u->dusun) }}')"><x-smart-image :src="$u->foto ? asset('storage/'.$u->foto) : null" :alt="'Foto UMKM '.$u->nama_umkm" class="aspect-video"/><div class="p-5"><span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-900">{{ $u->kategori }}</span><h2 class="mt-3 text-xl font-bold text-blue-900">{{ $u->nama_umkm }}</h2><p class="mt-2 text-sm text-slate-500">{{ $u->pemilik }} · {{ $u->dusun }} {{ $u->rt_rw }}</p><p class="mt-3 text-slate-600">{{ $u->deskripsi }}</p>@if($u->latitude&&$u->longitude)<a class="mt-4 inline-block font-bold text-blue-900" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination={{ $u->latitude }},{{ $u->longitude }}">Petunjuk Arah (Google Maps)</a>@endif</div></article>@endforeach</div>
<section class="mt-14"><h2 class="section-kicker">FAQ UMKM</h2><div class="mt-6 space-y-3">@forelse($faqs as $faq)<article x-data="{open:false}" class="content-card"><button @click="open=!open" class="flex w-full justify-between p-5 text-left font-bold text-blue-900"><span>{{ $faq->pertanyaan }}</span><span x-text="open?'−':'+'"></span></button><div x-show="open" class="rich-content px-5 pb-5">{!! $faq->jawaban !!}</div></article>@empty<p class="empty-state">FAQ UMKM belum tersedia.</p>@endforelse</div></section></section>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{const map=L.map('umkm-map').setView([-7.43,110.93],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap'}).addTo(map);const points=@json($umkms->filter(fn($u)=>$u->latitude&&$u->longitude)->values());points.forEach(u=>L.marker([u.latitude,u.longitude]).addTo(map).bindPopup(`<strong>${u.nama_umkm}</strong><br>${u.kategori}<br><a target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=${u.latitude},${u.longitude}">Petunjuk Arah (Google Maps)</a>`))});</script>@endsection